### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by flemton** [flemton/RecipeApp#19]
Dear reviewer, below is the link to our GitHub project

https://github.com/users/flemton/projects/2/views/1

Our group consisted of 2 members only and that's @JuanDiegoGuerra and me (@flemton )

**Comment by MahmoudBakr23** [comment]
Hi @flemton and @JuanDiegoGuerra 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done on dividing the tasks equally
- Well done on creating the required tasks for a 2 members team

Cheers, and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by flemton** [comment]
Dear @MahmoudBakr23, thank you very much for the review
